import React from 'react';
import { Control } from 'react-hook-form';
import {
  tenantQuestionnaireFormDataObject,
  ETenantQuestionnaireFields,
  booleanSelectFieldValues,
} from '../formUtils';
import { EBasicFieldType } from '@/models/forms';
import { BasicFieldController, ControlledSelect } from '@@/common/formFields';

interface IFormTenantFormBodyProps {
  control: Control<any>;
}

export const FormTenantFormBody: React.FC<IFormTenantFormBodyProps> = ({
  control,
}) => {
  return (
    <>
      <ControlledSelect
        valuesArray={booleanSelectFieldValues}
        control={control}
        fieldData={
          tenantQuestionnaireFormDataObject[
            ETenantQuestionnaireFields.RENTAL_AGREEMENT
          ]
        }
        noPlaceHolder
      />
      <BasicFieldController
        control={control}
        type={EBasicFieldType.multiLineText} // Assuming multiLineText for comments
        fieldData={
          tenantQuestionnaireFormDataObject[
            ETenantQuestionnaireFields.RENTAL_AGREEMENT_COMMENTS
          ]
        }
      />
      <ControlledSelect
        valuesArray={booleanSelectFieldValues}
        control={control}
        fieldData={
          tenantQuestionnaireFormDataObject[
            ETenantQuestionnaireFields.PROPERTY_INFORMATION
          ]
        }
        noPlaceHolder
      />
      <BasicFieldController
        control={control}
        type={EBasicFieldType.multiLineText}
        fieldData={
          tenantQuestionnaireFormDataObject[
            ETenantQuestionnaireFields.PROPERTY_INFORMATION_COMMENTS
          ]
        }
      />
      <ControlledSelect
        valuesArray={booleanSelectFieldValues}
        control={control}
        fieldData={
          tenantQuestionnaireFormDataObject[
            ETenantQuestionnaireFields.LEASE_SIGNING_PROCESS
          ]
        }
        noPlaceHolder
      />
      <BasicFieldController
        control={control}
        type={EBasicFieldType.multiLineText}
        fieldData={
          tenantQuestionnaireFormDataObject[
            ETenantQuestionnaireFields.LEASE_SIGNING_PROCESS_COMMENTS
          ]
        }
      />
      <ControlledSelect
        valuesArray={booleanSelectFieldValues}
        control={control}
        fieldData={
          tenantQuestionnaireFormDataObject[
            ETenantQuestionnaireFields.QUESTIONS_ADDRESSED
          ]
        }
        noPlaceHolder
      />
      <BasicFieldController
        control={control}
        type={EBasicFieldType.multiLineText}
        fieldData={
          tenantQuestionnaireFormDataObject[
            ETenantQuestionnaireFields.QUESTIONS_ADDRESSED_COMMENTS
          ]
        }
      />
      <ControlledSelect
        valuesArray={booleanSelectFieldValues}
        control={control}
        fieldData={
          tenantQuestionnaireFormDataObject[
            ETenantQuestionnaireFields.PROPERTY_CONDITION
          ]
        }
        noPlaceHolder
      />
      <BasicFieldController
        control={control}
        type={EBasicFieldType.multiLineText}
        fieldData={
          tenantQuestionnaireFormDataObject[
            ETenantQuestionnaireFields.PROPERTY_CONDITION_COMMENTS
          ]
        }
      />
      <ControlledSelect
        valuesArray={booleanSelectFieldValues}
        control={control}
        fieldData={
          tenantQuestionnaireFormDataObject[
            ETenantQuestionnaireFields.RECEIVED_INFORMATION
          ]
        }
        noPlaceHolder
      />
      <BasicFieldController
        control={control}
        type={EBasicFieldType.multiLineText}
        fieldData={
          tenantQuestionnaireFormDataObject[
            ETenantQuestionnaireFields.TRANSITION_PROBLEMS
          ]
        }
      />
      <BasicFieldController
        control={control}
        type={EBasicFieldType.rating}
        fieldData={
          tenantQuestionnaireFormDataObject[
            ETenantQuestionnaireFields.SATISFACTION_RATING
          ]
        }
      />
      <ControlledSelect
        valuesArray={booleanSelectFieldValues}
        control={control}
        fieldData={
          tenantQuestionnaireFormDataObject[
            ETenantQuestionnaireFields.MAINTENANCE_REQUESTS
          ]
        }
        noPlaceHolder
      />
      <BasicFieldController
        control={control}
        type={EBasicFieldType.multiLineText}
        fieldData={
          tenantQuestionnaireFormDataObject[
            ETenantQuestionnaireFields.MAINTENANCE_REQUESTS_COMMENTS
          ]
        }
      />
      <BasicFieldController
        control={control}
        type={EBasicFieldType.multiLineText}
        fieldData={
          tenantQuestionnaireFormDataObject[
            ETenantQuestionnaireFields.FIRST_IMPRESSION
          ]
        }
      />
    </>
  );
};
